### ISSUE TITLE
Finalizador de línea modo Unix

### ISSUE THREAD

**Issue by franciscopajares** [davidclothier/Cosmos_Http#2]
Hola David,

Gracias por subir el ejemplo.
Comentarte que el proyecto no compila porque el terminador de línea de los archivos SAMPLE_HTTP.SMD y SAMPLE_HTTP.SMD está en modo Unix (LF).
Hay que cambiarlo a modo Windows (CR + LF).

Un saludo.

**Comment by davidclothier** [comment]
Buenas de nuevo Paco.

Acabo de probar a clonar/compilar y sin problemas. Edito con Notepad++ y veo que sí tiene CRLF al final del archivo:

![Screenshot](https://i.imgur.com/uI1mJel.png)

Estoy viendo que tiene que ver algo con la configuración del siguiente archivo de git: _core.autocrlf_
o algún replace que hace github. Probaré a clonarlo en otros equipos.

Gracias por el aviso.

Un saludo.

**Comment by davidclothier** [comment]
Vale, @franciscopajares, efectivamente, si te bajas el repo sin clonarlo, aparece sólo LF

![Screenshot](https://i.imgur.com/ihMMJ5U.png)

Voy a mirar a tocar el fichero de configuración de git para que no lo convierta a LF como dice el [manual](https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration)

**Comment by davidclothier** [comment]
Solucionado:
`git config --global core.autocrf false`
